FROM mysql:5.7

MAINTAINER Malisa Ncube <malisa.n@turing.com>

ENV MYSQL_DATABASE 'turing'
ENV MYSQL_ROOT_PASSWORD 'root'
ENV MYSQL_USER 'turing'
ENV MYSQL_PASSWORD 'turing'

COPY ./sql/database.sql /docker-entrypoint-initdb.d/dump.sql

EXPOSE 3306/tcp